### ISSUE TITLE
ERROR Unable to load component

### ISSUE THREAD

**Issue by ananyevgv** [nonameplum/esphome_devices#1]
It is not possible to compile with the MQ component, it gives an error

cv.Required(CONF_PIN): pins.internal_gpio_analog_pin_schema,
AttributeError: module 'esphome.pins' has no attribute 'internal_gpio_analog_pin_schema'

**Comment by nonameplum** [comment]
@ananyevgv Yup, it seems like ESPHome has removed that pin schema https://github.com/esphome/esphome/pull/2303. I will try to find out what other pin schema could be used. Until then what you could try is to use the approach of ADC sensor: https://github.com/esphome/esphome/blob/dev/esphome/components/adc/sensor.py

so instead of:

```diff
def validate_adc_pin(value):
    if str(value).upper() == "VCC":
        return cv.only_on_esp8266("VCC")

    if str(value).upper() == "TEMPERATURE":
        return cv.only_on_rp2040("TEMPERATURE")

    if CORE.is_esp32:
        value = pins.internal_gpio_input_pin_number(value)
        variant = get_esp32_variant()
        if variant not in ESP32_VARIANT_ADC1_PIN_TO_CHANNEL:
            raise cv.Invalid(f"This ESP32 variant ({variant}) is not supported")

        if value not in ESP32_VARIANT_ADC1_PIN_TO_CHANNEL[variant]:
            raise cv.Invalid(f"{variant} doesn't support ADC on this pin")
        return pins.internal_gpio_input_pin_schema(value)

    if CORE.is_esp8266:
        from esphome.components.esp8266.gpio import CONF_ANALOG

        value = pins.internal_gpio_pin_number({CONF_ANALOG: True, CONF_INPUT: True})(
            value
        )

        if value != 17:  # A0
            raise cv.Invalid("ESP8266: Only pin A0 (GPIO17) supports ADC.")
        return pins.gpio_pin_schema(
            {CONF_ANALOG: True, CONF_INPUT: True}, internal=True
        )(value)

    if CORE.is_rp2040:
        value = pins.internal_gpio_input_pin_number(value)
        if value not in (26, 27, 28, 29):
            raise cv.Invalid("RP2040: Only pins 26, 27, 28 and 29 support ADC.")
        return pins.internal_gpio_input_pin_schema(value)

    raise NotImplementedError
...

- cv.Required(CONF_PIN): pins.internal_gpio_analog_pin_schema,
+ cv.Required(CONF_PIN): validate_adc_pin,
```

**Comment by ananyevgv** [comment]
In file included from src/esphome/components/mq/mq.cpp:2:
src/esphome/components/mq/mq.h:154:19: error: expected ')' before '*' token
  154 |   MQSensor(GPIOPin *pin, MQModel model, bool is_ESP8266, float rl);
      |           ~       ^~
      |                   )
src/esphome/components/mq/mq.h:166:3: error: 'GPIOPin' does not name a type; did you mean 'GPIEP'?
  166 |   GPIOPin *pin_;
      |   ^~~~~~~
      |   GPIEP
src/esphome/components/mq/mq.cpp:14:19: error: expected constructor, destructor, or type conversion before '(' token
   14 | MQSensor::MQSensor(GPIOPin *pin_, MQModel model, bool is_ESP8266, float rl) {
      |                   ^
src/esphome/components/mq/mq.cpp: In member function 'virtual void esphome::mq::MQSensor::setup()':
src/esphome/components/mq/mq.cpp:39:41: error: 'class esphome::mq::MQSensor' has no member named 'pin_'
   39 |                                   this->pin_->get_pin(), String(this->model_parameters_.model_name().c_str()));
      |                                         ^~~~
src/esphome/components/mq/mq.cpp: In member function 'virtual void esphome::mq::MQSensor::dump_config()':
src/esphome/components/mq/mq.cpp:75:28: error: 'class esphome::mq::MQSensor' has no member named 'pin_'
   75 |   LOG_PIN("  Pin: ", this->pin_);
      |                            ^~~~
src/esphome/components/mq/mq.cpp:75:3: error: 'LOG_PIN' was not declared in this scope; did you mean 'LOG_I'?
   75 |   LOG_PIN("  Pin: ", this->pin_);
      |   ^~~~~~~
      |   LOG_I
In file included from src/esphome/components/mq/mq.cpp:1:
src/esphome/components/mq/mq.cpp:79:41: error: initializer fails to determine size of '__pstr__'
   79 |     LOG_SENSOR("  ", it.gas_name().c_str(), it.sensor);
src/esphome/core/log.h:94:90: note: in definition of macro 'esph_log_config'
   94 |   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                          ^~~~~~~~~~~
src/esphome/components/sensor/sensor.h:14:5: note: in expansion of macro 'ESP_LOGCONFIG'
   14 |     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
      |     ^~~~~~~~~~~~~
src/esphome/core/log.h:192:28: note: in expansion of macro 'LOG_STR_ARG'
  192 | #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
      |                            ^~~~~~~~~~~
src/esphome/core/log.h:192:40: note: in expansion of macro 'LOG_STR'
  192 | #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
      |                                        ^~~~~~~
src/esphome/components/sensor/sensor.h:14:45: note: in expansion of macro 'LOG_STR_LITERAL'
   14 |     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
      |                                             ^~~~~~~~~~~~~~~
src/esphome/components/mq/mq.cpp:79:5: note: in expansion of macro 'LOG_SENSOR'
   79 |     LOG_SENSOR("  ", it.gas_name().c_str(), it.sensor);
      |     ^~~~~~~~~~
src/esphome/components/mq/mq.cpp:79:41: error: array must be initialized with a brace-enclosed initializer
   79 |     LOG_SENSOR("  ", it.gas_name().c_str(), it.sensor);
src/esphome/core/log.h:94:90: note: in definition of macro 'esph_log_config'
   94 |   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                          ^~~~~~~~~~~
src/esphome/components/sensor/sensor.h:14:5: note: in expansion of macro 'ESP_LOGCONFIG'
   14 |     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
      |     ^~~~~~~~~~~~~
src/esphome/core/log.h:192:28: note: in expansion of macro 'LOG_STR_ARG'
  192 | #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
      |                            ^~~~~~~~~~~
src/esphome/core/log.h:192:40: note: in expansion of macro 'LOG_STR'
  192 | #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
      |                                        ^~~~~~~
src/esphome/components/sensor/sensor.h:14:45: note: in expansion of macro 'LOG_STR_LITERAL'
   14 |     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
      |                                             ^~~~~~~~~~~~~~~
src/esphome/components/mq/mq.cpp:79:5: note: in expansion of macro 'LOG_SENSOR'
   79 |     LOG_SENSOR("  ", it.gas_name().c_str(), it.sensor);
      |     ^~~~~~~~~~
*** [/data/mq/.pioenvs/mq/src/esphome/components/mq/mq.cpp.o] Error 1

**Comment by ananyevgv** [comment]
it almost worked, I can't figure out the error:

error: 'class esphome::GPIOPin' has no member named 'get_pin'
   39 |                               this->pin_->get_pin(), String(this->model_parameters_.model_name().c_str()));

**Comment by ananyevgv** [comment]
![image](https://github.com/nonameplum/esphome_devices/assets/81970899/085c1cda-5350-472d-a4b4-fb5524bb8e62)
